name: github pages

on:
  push:
    branches:
      - develop  # Set a branch name to trigger deployment
    paths:
      - .github/workflows/**
      - docs/** # documentsフォルダ内が更新されたときに実施
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # rlespinasse/drawio-export-action@v2 を使うときに指定が必要

      # 公開用リポジトリ作成
      - name: Create gh-pages-dir
        run: |
          mkdir -p ./documents/publish

      # draw.io
      - name: Export draw.io
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: docs/drawio
          format: png
          output: ../../documents/publish/drawio
          transparent: true

      # デプロイ
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documents
