# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - develop
    paths:
      - .github/workflows/**
      - docs/** # documentsフォルダ内が更新されたときに実施
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # rlespinasse/drawio-export-action@v2 を使うときに指定が必要

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ユニットテスト用環境インストール
      - name: Install dependencies
        run: npm install

      # カバレッジ作成 -> astro の publicフォルダ内
      - name: Coverage
        run: npm run coverage

      # markdown エディタ用
      - name: Install dependencies
        run: npm install
        working-directory: docs/documents/astro

      # markdown 公開 (astro/dist)
      - name: Build Astro
        run: npm run build
        working-directory: docs/documents/astro

      # draw.io ※ 日本語は文字化けする  astro/dist 内にpngエクスポート
      - name: Export draw.io
        uses: rlespinasse/drawio-export-action@v2
        with:
          path: docs/drawio
          format: png
          output: ../documents/astro/dist/drawio-assets
          transparent: false
          action-mode: all



      # アーティファクト作成 (astro/dist フォルダを公開用に梱包)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/documents/astro/dist/



  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
